### PR TITLE
Fcrepo 2407, etag reformatting

### PR DESCRIPTION
**Pull request by bbpennel**
Same as #24 but with some reformatting assistance one etag setting methods to allow for easier reuse of response etag.

### CODE REVIEW

**Comment by bbpennel** [comment]
Okay, #24 is basically the same thing but without the hidden functionality if you would rather merge that one.

**Comment by awoods** [comment]
Instead of using ETags on RDF sources, the suggestion coming out of today's [Fedora Tech Meeting](https://wiki.duraspace.org/display/FF/2017-03-02+-+Fedora+Tech+Meeting) was to instead rely on the `If-Modified-Since` header.

**Comment by acoburn** [comment]
+1 on using `If-Modified-Since`. There are also use cases for `If-Match`, so I'd like to have that, too.

**Comment by bbpennel** [comment]
Closing in favor of #24

**Pull request closed without merging**
